# Generated by Django 2.0.6 on 2018-06-15 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_auto_20180613_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_pk', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
                ('final_destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.Destiny')),
                ('property_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'scheduleds',
                'verbose_name': 'scheduled',
            },
        ),
    ]
