# Generated by Django 2.0.6 on 2018-06-16 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180616_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
