# Generated by Django 2.0.6 on 2018-06-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180616_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='property_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_get', to='car.Users'),
        ),
    ]
