# Generated by Django 2.0.6 on 2018-06-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0010_auto_20180612_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_pk', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Users')),
            ],
            options={
                'verbose_name_plural': 'cars',
                'verbose_name': 'car',
            },
        ),
    ]
