# Generated by Django 2.0.6 on 2018-06-16 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='user_schedule_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
