# Generated by Django 2.0.6 on 2018-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_schedule', '0002_auto_20180616_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='user_schedule_pk',
        ),
        migrations.AddField(
            model_name='userschedule',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
