# Generated by Django 2.0.6 on 2018-06-16 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_schedule', '0003_auto_20180616_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='userschedule',
            name='user_schedule_pk',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
