# Generated by Django 2.0.6 on 2018-06-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('destiny_pk', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('complement', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('federal_unit', models.CharField(max_length=2)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'destinys',
                'verbose_name': 'destiny',
            },
        ),
    ]
